SweetSavoryTreats/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SweetSavoryTreats.Models
{
  public class Treat
  {
    public int TreatId { get; set; }
    [Required(ErrorMessage = "The Treat's Name is the most important information!")]
    public string TreatName { get; set; }
    public string TreatIngredient { get; set; }

    [Required(ErrorMessage = "The Treat Rate is required!")]
    public string TreatRate { get; set; }

    public List<TreatFlavor> JoinEntities { get; set; }

    public List<OrderTreat> OTJoinEntities { get; set; }   
    public ApplicationUser User { get; set; } 
  }
}

SweetSavoryTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using SweetSavoryTreats.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace SweetSavoryTreats.Controllers
{
  [Authorize]

  public class FlavorsController : Controller
  {
    private readonly SweetSavoryTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, SweetSavoryTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    
    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Flavor> allFlavors = _db.Flavors
                            .OrderBy(flavor => flavor.FlavorName)
                            .ToList();
      return View(allFlavors);
    }

    public async Task<ActionResult> MyFlavors()
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      List<Flavor> userFlavors = _db.Flavors
                                .Where(entry =>entry.User.Id == currentUser.Id)
                                .OrderBy(flavor => flavor.FlavorName)
                                .ToList();
      return View(userFlavors);
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Flavor thisFlavor = _db.Flavors
          .Include(flavor => flavor.JoinEntities)
          .ThenInclude(join => join.Treat)
          .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor)
    {
      if (!ModelState.IsValid)
      {
        return View(flavor);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

        flavor.User = currentUser;

        _db.Flavors.Add(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }

    }
    
    public async Task<ActionResult> AddTreat(int id)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      // flavor should only match the user's treats
      List<Treat> userTreats = _db.Treats
                                .Where(e => e.User.Id == currentUser.Id)
                                .OrderBy(treat => treat.TreatRate)
                                .ToList();
                                
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);

      ViewBag.TreatId = new SelectList(userTreats, "TreatId", "TreatName");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int treatId)
    {
      #nullable enable
      TreatFlavor? joinEntity = _db.TreatFlavors.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
      #nullable disable
      
      if (joinEntity == null && treatId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { TreatId = treatId, FlavorId = flavor.FlavorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    public async Task<ActionResult> Edit(int id)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      if (thisFlavor.User == currentUser)
      {
        return View(thisFlavor);
      }
      else 
      {
        return RedirectToAction("Index");
      }
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      if (!ModelState.IsValid)
      {
        return View(flavor);
      }
      else
      {
        _db.Flavors.Update(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public async Task<ActionResult> Delete(int id)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      if (thisFlavor.User == currentUser)
      {
        return View(thisFlavor);
      }
      else 
      {
        return RedirectToAction("Index");
      }
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");

    }

    [HttpPost]
    public async Task<ActionResult> DeleteJoin(int joinId)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(entry => entry.FlavorId == joinEntry.FlavorId);
      if (thisFlavor.User == currentUser)
      {
        _db.TreatFlavors.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      else
      {
        return RedirectToAction("Index", "Home");
      }
    }
    
  }
}

SweetSavoryTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using SweetSavoryTreats.Models;
using System.Collections.Generic;
using System.Linq;

using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace SweetSavoryTreats.Controllers
{
  [Authorize]

  public class TreatsController : Controller
  {
    
    private readonly SweetSavoryTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, SweetSavoryTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    
    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Treat> allTreats = _db.Treats
      .OrderBy(treat => treat.TreatRate).ToList();                            
      return View(allTreats);
    }

    public async Task<ActionResult> MyTreats()
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      List<Treat> userTreats = _db.Treats
      .Where(entry => entry.User.Id == currentUser.Id)
      .OrderBy(treat => treat.TreatRate).ToList();                            
      return View(userTreats);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat)
    {
      if (!ModelState.IsValid)
      {
        return View(treat);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

        treat.User = currentUser;

        _db.Treats.Add(treat);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      
    }
   
    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Treat thisTreat = _db.Treats
                             .Include(treat => treat.JoinEntities)
                             .ThenInclude(join => join.Flavor)
                             .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    public async Task<ActionResult> Edit(int id)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      if (thisTreat.User == currentUser)
      {
        return View(thisTreat);
      }
      else
      {
        return RedirectToAction("Index");
      }
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      if (!ModelState.IsValid)
      {
        return View(treat);
      }
      else
      {
        _db.Treats.Update(treat);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public async Task<ActionResult> Delete(int id)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      if (thisTreat.User == currentUser)
      {
        return View(thisTreat);
      }
      else
      {
        return RedirectToAction("Index");
      }
      
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public async Task<ActionResult> AddFlavor(int id)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      List<Flavor> allFlavors = _db.Flavors
                                .OrderBy(flavor => flavor.FlavorName)
                                .ToList();

      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      
      ViewBag.FlavorId = new SelectList(allFlavors, "FlavorId", "FlavorName");
      
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int flavorId)
    {
      #nullable enable
      TreatFlavor? joinEntity = _db.TreatFlavors.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
      #nullable disable

      if (joinEntity == null && flavorId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { FlavorId = flavorId, TreatId = treat.TreatId });
        _db.SaveChanges();
      }

      return RedirectToAction("Details", new { id = treat.TreatId });
    }  

    [HttpPost]
    public async Task<ActionResult> DeleteJoin(int joinId)
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);

      TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      Treat thisTreat = _db.Treats.FirstOrDefault(entry => entry.TreatId == joinEntry.TreatId);

      if (thisTreat.User == currentUser)
      {
        _db.TreatFlavors.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
      else
      {
        return RedirectToAction("Index", "Home");
      }
    }

  }
}
 

SweetSavoryTreats/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Treat

<h2>Add a flavor</h2>

<h4>Add a flavor to this treat: @Html.DisplayFor(model => model.TreatName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

SweetSavoryTreats/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Treat

<h4>Add a new treat</h4>

<p>@Html.ValidationMessageFor(m=>m.TreatName,"", new {@class = "text-danger", @style = "font-weight: 600;"})</p>
<p>@Html.ValidationMessageFor(m=>m.TreatRate,"", new {@class = "text-danger", @style = "font-weight: 600;"})</p>

@using (Html.BeginForm())
{
  <p>Treat Name: @Html.TextBoxFor(model => model.TreatName)</p>
  <p>Treat Rating: @Html.TextBoxFor(model => model.TreatRate)</p>
  <p>Treat Ingredients: @Html.TextBoxFor(model => model.TreatIngredient)</p>

  <input type="submit" value="Add new treat" class="btn btn-default" />
}

<p>@Html.ActionLink("Show all treats", "Index")</p>

SweetSavoryTreats/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Treat

<h2>Are you sure you want to delete this treat?</h2>

@Html.DisplayNameFor(model => model.TreatName): @Html.DisplayFor(model => model.TreatName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

SweetSavoryTreats/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using SweetSavoryTreats.Models
@model SweetSavoryTreats.Models.Treat

<h2>Treat Details</h2>
<hr />
<h3>Treat Name: @Html.DisplayFor(model => model.TreatName)</h3>

<p>Treat Rating: @Html.DisplayFor(model => model.TreatRate)</p>
<p>Ingredients: @Html.DisplayFor(model => model.TreatIngredient)</p>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This treat does not have any flavors.</p>
}
else
{
  <h4>Flavors the treat has:</h4>
  <ul>
  @foreach(TreatFlavor join in Model.JoinEntities)
  {
    <li>@join.Flavor.FlavorName</li>

    @using (Html.BeginForm("DeleteJoin", "Treats"))
    {
      @Html.Hidden("joinId", @join.TreatFlavorId)
      @if (User.Identity.IsAuthenticated)
      {
        <input type="submit" value="Remove"/>
      }
    }
    
  }
  </ul>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

<p>@Html.ActionLink("Add a Flavor", "AddFlavor", new { id = Model.TreatId })</p>

<p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId })</p>

<p>@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId })</p>

SweetSavoryTreats/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model SweetSavoryTreats.Models.Treat

<h4>Edit this Treat: @Html.DisplayFor(m => m.TreatName)</h4>

<p>@Html.ValidationMessageFor(m=>m.TreatName,"", new {@class = "text-danger", @style = "font-weight: 600;"})</p>
<p>@Html.ValidationMessageFor(m=>m.TreatRate,"", new {@class = "text-danger", @style = "font-weight: 600;"})</p>

@using (Html.BeginForm())
{
  @Html.HiddenFor(m => m.TreatId)

  <p>Treat Name: @Html.EditorFor(model => model.TreatName)</p>
  <p>Treat Rating: @Html.EditorFor(model => model.TreatRate)</p>
  <p>Treat Ingredients: @Html.EditorFor(model => model.TreatIngredient)</p>
 
  <input type="submit" value="Save Changes" class="btn btn-default" />
}

<p>@Html.ActionLink("Back to treats","Index")<p>

SweetSavoryTreats/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using SweetSavoryTreats.Models;

<h1>Treats</h1>

@if (@Model.Count == 0)
{
  <h3>No treats have been added yet!</h3>
} 

<ul>
  @foreach(Treat treat in Model)
  {
    <li>@Html.ActionLink($"{treat.TreatName}", "Details", new { id = treat.TreatId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new treat", "Create")</p>
<p>@Html.ActionLink("Create a Flavor", "Create", "Flavors")</p>

@if (User.Identity.IsAuthenticated)
{
  <p>Hello @User.Identity.Name!</p>
  
  <p>@Html.ActionLink("View my treats", "MyTreats")</p>
}

SweetSavoryTreats/Views/Treats/MyTreats.cshtml
@{
  Layout = "_Layout";
}

@using SweetSavoryTreats.Models;

<h1>@User.Identity.Name's Treats</h1>

@if (@Model.Count == 0)
{
  <h3>No treats have been added yet!</h3>
} 

<ul>
  @foreach(Treat treat in Model)
  {
    <li>@Html.ActionLink($"{treat.TreatName}", "Details", new { id = treat.TreatId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new treat", "Create")</p>
<p>@Html.ActionLink("Create a flavor", "Create", "Flavors")</p>
<p>@Html.ActionLink("Treats Index", "Index")</p>